# Ollama/OpenAI 兼容接口参数
chat_service:
  ros__parameters:
    base_url: "http://localhost:11434/v1"   # 本地 Ollama
    api_key: "ollama"                       # 本地随意写；阿里云填真实 key
    # base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # 阿里云示例
    # api_key: ""
    # use_model: "deepseek-r1:1.5b"
    use_model: "qwen2.5:3b"
    # use_model: ""                           # 空 = 自动选第一个；也可写成 "deepseek-r1"
    stream: false                           # true = 流式
    temperature: 0.5
    history_length: 10
    knowledge_base_path: "/home/guest/offline_chat/src/wheeltec_mic/wheeltec_mic_aiui/database"

ollama_topic_server:
  ros__parameters:
    base_url: "http://localhost:11434/v1"   # 本地 Ollama
    api_key: "ollama"                       # 本地随意写；阿里云填真实 key
    #base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"  # 阿里云示例
    #api_key: ""
    use_model: "qwen2.5:3b"                           # 空 = 自动选第一个；也可写成 "llama3.1:8b"
    stream: false                           # true = lconnc
    temperature: 0.5
    history_length: 10


    ### Couldn't find '/home/zl/snap/ollama/95/.ollama/id_ed25519'. Generating new private key.
    ### Your new public key is: 
    ### ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDFDZnwWpdDcGeVIJ3/FucdkbDhnmBb1hooFYcZymw8W
    